### ISSUE TITLE
Kernel error

### ISSUE THREAD

**Issue by kushalchauhan98** [brendan-rius/jupyter-c-kernel#17]
I performed the manual installation as given in the "README.md". But I am getting Kernel error during kernel start.
**Failed to start the kernel**
**Unknown server error**

``` python
Traceback (most recent call last):
  File "C:\Program Files\Anaconda3\lib\site-packages\notebook\base\handlers.py", line 457, in wrapper
    result = yield gen.maybe_future(method(self, *args, **kwargs))
  File "C:\Program Files\Anaconda3\lib\site-packages\tornado\gen.py", line 1015, in run
    value = future.result()
  File "C:\Program Files\Anaconda3\lib\site-packages\tornado\concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "C:\Program Files\Anaconda3\lib\site-packages\tornado\gen.py", line 1021, in run
    yielded = self.gen.throw(*exc_info)
  File "C:\Program Files\Anaconda3\lib\site-packages\notebook\services\sessions\handlers.py", line 62, in post
    kernel_id=kernel_id))
  File "C:\Program Files\Anaconda3\lib\site-packages\tornado\gen.py", line 1015, in run
    value = future.result()
  File "C:\Program Files\Anaconda3\lib\site-packages\tornado\concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "C:\Program Files\Anaconda3\lib\site-packages\tornado\gen.py", line 1021, in run
    yielded = self.gen.throw(*exc_info)
  File "C:\Program Files\Anaconda3\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 79, in create_session
    kernel_name)
  File "C:\Program Files\Anaconda3\lib\site-packages\tornado\gen.py", line 1015, in run
    value = future.result()
  File "C:\Program Files\Anaconda3\lib\site-packages\tornado\concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "C:\Program Files\Anaconda3\lib\site-packages\tornado\gen.py", line 1021, in run
    yielded = self.gen.throw(*exc_info)
  File "C:\Program Files\Anaconda3\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 92, in start_kernel_for_session
    self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
  File "C:\Program Files\Anaconda3\lib\site-packages\tornado\gen.py", line 1015, in run
    value = future.result()
  File "C:\Program Files\Anaconda3\lib\site-packages\tornado\concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "C:\Program Files\Anaconda3\lib\site-packages\tornado\gen.py", line 285, in wrapper
    yielded = next(result)
  File "C:\Program Files\Anaconda3\lib\site-packages\notebook\services\kernels\kernelmanager.py", line 87, in start_kernel
    super(MappingKernelManager, self).start_kernel(**kwargs)
  File "C:\Program Files\Anaconda3\lib\site-packages\jupyter_client\multikernelmanager.py", line 110, in start_kernel
    km.start_kernel(**kwargs)
  File "C:\Program Files\Anaconda3\lib\site-packages\jupyter_client\manager.py", line 243, in start_kernel
    **kw)
  File "C:\Program Files\Anaconda3\lib\site-packages\jupyter_client\manager.py", line 189, in _launch_kernel
    return launch_kernel(kernel_cmd, **kw)
  File "C:\Program Files\Anaconda3\lib\site-packages\jupyter_client\launcher.py", line 123, in launch_kernel
    proc = Popen(cmd, **kwargs)
  File "C:\Program Files\Anaconda3\lib\subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "C:\Program Files\Anaconda3\lib\subprocess.py", line 1224, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

OS - Win10
Python distro - Anaconda3 with Python 3.5.2

EDIT:
I also tried it in my Python 2.7.12 environment in Anaconda. The same problem there too.

**Failed to start the kernel**
**Unknown server error**

`````` python
Traceback (most recent call last):
  File "C:\Program Files\Anaconda3\envs\python27\lib\site-packages\notebook\base\handlers.py", line 457, in wrapper
    result = yield gen.maybe_future(method(self, *args, **kwargs))
  File "C:\Program Files\Anaconda3\envs\python27\lib\site-packages\tornado\gen.py", line 1015, in run
    value = future.result()
  File "C:\Program Files\Anaconda3\envs\python27\lib\site-packages\tornado\concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "C:\Program Files\Anaconda3\envs\python27\lib\site-packages\tornado\gen.py", line 1021, in run
    yielded = self.gen.throw(*exc_info)
  File "C:\Program Files\Anaconda3\envs\python27\lib\site-packages\notebook\services\sessions\handlers.py", line 62, in post
    kernel_id=kernel_id))
  File "C:\Program Files\Anaconda3\envs\python27\lib\site-packages\tornado\gen.py", line 1015, in run
    value = future.result()
  File "C:\Program Files\Anaconda3\envs\python27\lib\site-packages\tornado\concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "C:\Program Files\Anaconda3\envs\python27\lib\site-packages\tornado\gen.py", line 1021, in run
    yielded = self.gen.throw(*exc_info)
  File "C:\Program Files\Anaconda3\envs\python27\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 79, in create_session
    kernel_name)
  File "C:\Program Files\Anaconda3\envs\python27\lib\site-packages\tornado\gen.py", line 1015, in run
    value = future.result()
  File "C:\Program Files\Anaconda3\envs\python27\lib\site-packages\tornado\concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "C:\Program Files\Anaconda3\envs\python27\lib\site-packages\tornado\gen.py", line 1021, in run
    yielded = self.gen.throw(*exc_info)
  File "C:\Program Files\Anaconda3\envs\python27\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 92, in start_kernel_for_session
    self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
  File "C:\Program Files\Anaconda3\envs\python27\lib\site-packages\tornado\gen.py", line 1015, in run
    value = future.result()
  File "C:\Program Files\Anaconda3\envs\python27\lib\site-packages\tornado\concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "C:\Program Files\Anaconda3\envs\python27\lib\site-packages\tornado\gen.py", line 285, in wrapper
    yielded = next(result)
  File "C:\Program Files\Anaconda3\envs\python27\lib\site-packages\notebook\services\kernels\kernelmanager.py", line 87, in start_kernel
    super(MappingKernelManager, self).start_kernel(**kwargs)
  File "C:\Program Files\Anaconda3\envs\python27\lib\site-packages\jupyter_client\multikernelmanager.py", line 110, in start_kernel
    km.start_kernel(**kwargs)
  File "C:\Program Files\Anaconda3\envs\python27\lib\site-packages\jupyter_client\manager.py", line 243, in start_kernel
    **kw)
  File "C:\Program Files\Anaconda3\envs\python27\lib\site-packages\jupyter_client\manager.py", line 189, in _launch_kernel
    return launch_kernel(kernel_cmd, **kw)
  File "C:\Program Files\Anaconda3\envs\python27\lib\site-packages\jupyter_client\launcher.py", line 123, in launch_kernel
    proc = Popen(cmd, **kwargs)
  File "C:\Program Files\Anaconda3\envs\python27\lib\subprocess.py", line 711, in __init__
    errread, errwrite)
  File "C:\Program Files\Anaconda3\envs\python27\lib\subprocess.py", line 959, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified```
``````

**Comment by kushalchauhan98** [comment]
Hello? Anybody home?

**Comment by msgoff** [comment]
these steps worked for me
sudo pip3 install jupyter-c-kernel
git clone https://github.com/brendan-rius/jupyter-c-kernel.git
cd jupyter-c-kernel/
jupyter-kernelspec install c_spec/
sudo pip3 install ipykernel
jupyter-notebook

**Comment by EWouters** [comment]
I have the same problem. I guess there is no windows support??

**Comment by HunterYIboHu** [comment]
I have the same problem... and I use windows 10 too.
OS - Win10
Python distro - Python 3.5.1 [MSC v.1900 64 bit (AMD64)] on win32
Jupyter version -
Metadata-Version: 2.0
Name: jupyter
Version: 1.0.0

**Comment by kushalchauhan98** [comment]
I have been using Linux for a while now; so I can't test this solution and tell you that it'll definitely work, but I just think it might. 
In the python script -   "C:\Program Files\Anaconda3\envs\python27\lib\site-packages\jupyter_client\launcher.py", change line 123 (where the error arises from) from this:
                           proc = Popen(cmd, **kwargs)
To this:
                           proc = Popen(cmd, **kwargs, shell=True)

I have worked with the subprocess module for sometime, and in Windows, I had to invariably pass the additional 'shell=True' argument in every Popen() call (even where it isn't supposed to be there) in order to make it work. I think it is a subprocess-Windows problem, and this solution is a dirty, temporary fix. 
Could you try this fix and post back here?

**Comment by HunterYIboHu** [comment]
I have tried this fix and change the line 123 into this:
```
proc = Popen(cmd, shell=True, **kwargs)
```
but it doesn't work.
I guess the key is `kernel.json`, I found that many of the wrong code point to a json content like this:
```
[D 2016-04-29 09:21:07.343 user1 manager:241] Starting kernel: ['python3', '-m', 'c_kernel', '-f', '/home/user1/.local/share/jupyter/runtime/kernel-09670651-81\
9e-4c67-b185-6b3b8cfd99f5.json']
```
I try to change the content of `kernel.json` in the downloaded `jupyter-c-kernel`(like step 4, path is  `C:\Users\HuYibo\jupyter-c-kernel\c_spec\`), but the change do not work on this error...
Maybe the true `kernel.json` is in other place. Anyone who post your position of `kernel.json` would help a lot:)
@kushalchauhan98

**Comment by HunterYIboHu** [comment]
I found the true `kernel.json` is in `C:\ProgramData\jupyter\kernels\c_spec`, and after editing it into:
```
{
  "argv": [
    "python",
    "-m",
    "jupyter_c_kernel",
    "-f",
    "{connection_file}"
  ],
  "display_name": "C",
  "language": "c"
}
```
I fix this kernel error.

**Comment by petebachant** [comment]
I'm getting this error on Windows too. @HunterYIboHu could you submit a PR?

**Comment by engyasin** [comment]
me too have the same problem , jupyter4 , python 2.7 , gcc ,

**Comment by denisb** [comment]
On Windows 10, it works (for me) with the Ubuntu Windows Subsystem for Linux (WSL) but need  "master.c" bug repair (see other thread).

(first, I've tried Anaconda, and Windows install, but got bugs : "kernet error", "master.c", ...)
Jupyter 4.4.0
gcc 4.8.4
python 2.7.6 and python 3.4.3 (both needed ?)

**Comment by iamyash1th** [comment]
I have a similar issue on Windows 10 with Python 3.6 installation through Jupyter. Can someone help?

**Comment by iamyash1th** [comment]
This link solved my issue.

https://github.com/jupyter/jupyter/issues/147
