### ISSUE TITLE
Extra information to install

### ISSUE THREAD

**Issue by MarioJose** [brendan-rius/jupyter-c-kernel#38]
Hi,

I have some problems to install *c-kernel* with *step-by-step* section information.

First, I have python 2 and 3 installed, but only 3 has ipykernel. Then, I needed to use *pip3* to install. When I try to install with it I get an error:

```
$ install_c_kernel 
Installing IPython kernel spec
Traceback (most recent call last):
  File "/home/myuser/.local/bin/install_c_kernel", line 81, in <module>
    main(argv=sys.argv)
  File "/home/myuser/.local/bin/install_c_kernel", line 77, in main
    install_my_kernel_spec(user=user, prefix=prefix)
  File "/home/myuser/.local/bin/install_c_kernel", line 32, in install_my_kernel_spec
    KernelSpecManager().install_kernel_spec(td, 'bash', user=user, replace=True, prefix=prefix)
  File "/usr/lib/python3/dist-packages/jupyter_client/kernelspec.py", line 269, in install_kernel_spec
    shutil.copytree(source_dir, destination)
  File "/usr/lib/python3.5/shutil.py", line 315, in copytree
    os.makedirs(dst)
  File "/usr/lib/python3.5/os.py", line 231, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.5/os.py", line 231, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.5/os.py", line 241, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/usr/local/share/jupyter'
```

I solved using *--user* flag in *install_c_kernel*:

```
$ install_c_kernel --user
Installing IPython kernel spec

$ jupyter-kernelspec list
Available kernels:
  bash       /home/myuser/.local/share/jupyter/kernels/bash
  ir         /home/myuser/.local/share/jupyter/kernels/ir
  python3    /usr/share/jupyter/kernels/python3
```

Except in this list *c* kernel is shown as *bash*, when I open *jupyter* it is shown as *c*.

Maybe is better add this extra information in *step-by-step* section. Maybe a note to use *pip* or *pip3* and *--user* flag.

All the best,

Mario

**Comment by MatheusAMG** [comment]
You are great
