### ISSUE TITLE
Docker latest cannot change password, 500 server error with jupyter_notebook_config.json not found.

### ISSUE THREAD

**Issue by zhchaoxing** [brendan-rius/jupyter-c-kernel#72]
When running docker I used sudo and it didn't help.

[E 01:09:13.027 NotebookApp] Uncaught exception POST /login?next=%2Ftree%3F (192.168.28.114)
    HTTPServerRequest(protocol='http', host='192.168.28.189:8888', method='POST', uri='/login?next=%2Ftree%3F', version='HTTP/1.1', remote_ip='192.168.28.114')
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.6/site-packages/tornado/web.py", line 1541, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/opt/conda/lib/python3.6/site-packages/notebook/auth/login.py", line 88, in post
        set_password(new_password, config_file=config_file)
      File "/opt/conda/lib/python3.6/site-packages/notebook/auth/security.py", line 148, in set_password
        config.NotebookApp.password = hashed_password
      File "/opt/conda/lib/python3.6/contextlib.py", line 88, in __exit__
        next(self.gen)
      File "/opt/conda/lib/python3.6/site-packages/notebook/auth/security.py", line 131, in persist_config
        with io.open(config_file, 'w', encoding='utf8') as f:
    FileNotFoundError: [Errno 2] No such file or directory: '/home/jovyan/.jupyter/jupyter_notebook_config.json'
[E 01:09:13.047 NotebookApp] {
      "Host": "192.168.28.189:8888",
      "Connection": "keep-alive",
      "Content-Length": "148",
      "Cache-Control": "max-age=0",
      "Origin": "http://192.168.28.189:8888",
      "Upgrade-Insecure-Requests": "1",
      "Dnt": "1",
      "Content-Type": "application/x-www-form-urlencoded",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36",
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
      "Referer": "http://192.168.28.189:8888/login?next=%2Ftree%3F",
      "Accept-Encoding": "gzip, deflate",
      "Accept-Language": "zh-ID,zh;q=0.9,en-US;q=0.8,en;q=0.7,zh-CN;q=0.6,zh-TW;q=0.5",
      "Cookie": "_ga=GA1.1.1017422024.1597508361; agh_session=5e9a250517092fa28760e1ea50622f78ba95958ee4c9b9a27b9cbb9ed0e3bff7; _gid=GA1.1.1612420344.1598258879; _xsrf=2|e5e8412d|996fcc4c01c24f5688eddd905bc27665|1598281516; username-192-168-28-189-10000=\"2|1:0|10:1598282262|29:username-192-168-28-189-10000|44:YWNlZjIwNzZmNmIwNDI0MWIxNWYxMmE4YWI4N2RmYzg=|ab50890dfb27b20e7685f514b640fbb5cf699952d0181839e82b3e66bdacdf28\""
    }
[E 01:09:13.047 NotebookApp] 500 POST /login?next=%2Ftree%3F (192.168.28.114) 22.95ms referer=http://192.168.28.189:8888/login?next=%2Ftree%3F

**Comment by zhengfan2014** [comment]
可以参考这里：）
https://my.oschina.net/u/2306127/blog/3133081
